### ISSUE TITLE
Bug when using findall

### ISSUE THREAD

**Issue by washcycle** [rscarvalho/pyregex#19]
I was unable to get the correct results from the following lines of code, I tested them in python 3.4, and 2.7.6 and got the correct results.

    import re
    DATA = "Hey, you - what are you doing here!?"
    print re.findall(r"[\w']+", DATA)
    # Prints ['Hey', 'you', 'what', 'are', 'you', 'doing', 'here']

**Comment by rscarvalho** [comment]
@washcycle the bug has been fixed and the code is live. Thanks for the report and sorry for the LONG time to fix it.
